-- Script generated by Redgate Compare v1.19.3.12605
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.knight_redgate...';END$$;
DROP TABLE public.knight_redgate;

SET check_function_bodies = true;
